- Renamed permissions variable. - Added variable to set owner of media dirs. - Added permissions and owner of media dirs parameters. - Added self install script (to show exceptions) - Refactored files structure. - Refactored commands structure. - Add input file mageshell.

diff --git a/bin/mageinstall-init b/bin/mageinstall-init
--- a/bin/mageinstall-init
+++ b/bin/mageinstall-init
@@ -6,4 +6,5 @@ if [ -L $CURRENT"/mageinstall-init" ] ; then
   # I didn't find more right way to get a path of the real file
   SCRIPT_DIR=$(cd "$(dirname "$0")/../andkirby/mageinstall"; pwd)
 fi
-bash "$SCRIPT_DIR/src/init.sh" $@
+echo "Error: mageinstall-init command is deprecated since 4.0 version. Please use 'mageshell install init'."
+exit 1
diff --git a/bin/mageinstall-test b/bin/mageinstall-test
--- a/bin/mageinstall-test
+++ b/bin/mageinstall-test
@@ -6,4 +6,5 @@ if [ -L $CURRENT"/mageinstall-test" ] ; then
     # I didn't find more right way to get a path of the real file
     SCRIPT_DIR=$(cd "$(dirname "$0")/../andkirby/mageinstall"; pwd)
 fi
-bash "$SCRIPT_DIR/src/params-test.sh" $@
+echo "Error: mageinstall-test command is deprecated since 4.0 version. Please use 'mageshell install test'."
+exit 1
